# Default values for urlsafe
namespace: sfwcheck
createNamespace: true
replicaCount: 3

image:
  repository: gajuambi/urlsafe
  pullPolicy: Always
  tag: "latest"

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "500m"

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
  targetMemoryUtilizationPercentage: 70

nameOverride: ""
fullnameOverride: ""
