apiVersion: apps/v1
kind: Deployment
metadata:
  name: urlsafe
  labels:
    app: urlsafe
spec:
  replicas: 3
  selector:
    matchLabels:
      app: urlsafe
  template:
    metadata:
      labels:
        app: urlsafe
    spec:
      containers:
      - name: urlsafe
        image: gajuambi/urlsafe:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: urlsafe
spec:
  selector:
    app: urlsafe
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
